export const GET_ALL_GAMES = 'GET_ALL_GAMES'
export const GET_INITIAL_GAMES= 'GET_INITIAL_GAMES'
export const GET_GAME_BY_ID = 'GET_GAME_BY_ID'
export const GET_PAGES_PER_GAME = 'GET_PAGES_PER_GAME'

export const INCREASE_PAGE= 'INCREASE_PAGE'
export const DECREASE_PAGE= 'DECREASE_PAGE'
export const GET_INITIAL_GAMES_PAGE= 'GET_INITIAL_GAMES_PAGE'
export const GET_FILTERED_GAMES = 'GET_FILTERED_GAMES'

export const GET_PLATFORMS_GENRES = 'GET_PLATFORMS_GENRES'