export const GET_ALL_GAMES = 'GET_ALL_GAMES'
export const GET_INITIAL_GAMES= 'GET_INITIAL_GAMES'
export const GET_GAME_BY_ID = 'GET_GAME_BY_ID'
export const GET_CURRENT_PAGES = 'GET_CURRENT_PAGES'
export const RESTART_CURRENT_PAGE = 'RESTART_CURRENT_PAGE'
export const SEARCH_GAME = 'SEARCH_GAME'
export const CREATE_GAME = 'CREATE_GAME'
export const DELETE_GAME = 'DELETE_GAME'

export const INCREASE_PAGE= 'INCREASE_PAGE'
export const DECREASE_PAGE= 'DECREASE_PAGE'
export const CHANGE_PAGE = 'CHANGE_PAGE' //move from page 3 to 1, for example
export const GET_GAMES_PAGE= 'GET_GAMES_PAGE'
export const FILTER_GAMES = 'FILTER_GAMES'

export const GET_FAVORITES = 'GET_FAVORITES'
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'

export const GET_PLATFORMS_GENRES = 'GET_PLATFORMS_GENRES'

export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE'